# Generated by Django 4.2.28 on 2026-03-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
