# Generated by Django 4.2.28 on 2026-03-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_subscribed_on_subscription_subscribed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
