# Generated by Django 4.2.28 on 2026-03-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_course_usersubscription_courseactivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseactivity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
