# Generated by Django 4.2.28 on 2026-03-13 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_courseactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
