# Generated by Django 4.2.28 on 2026-03-16 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0018_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=10)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ear_training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
