# Generated by Django 4.2.28 on 2026-03-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_eartrainingprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EarTrainingProgress',
        ),
    ]
