# Generated by Django 4.2.28 on 2026-03-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_chordscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChordScore',
        ),
    ]
