# Generated by Django 4.2.28 on 2026-03-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_delete_chordscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordmelodyprogress',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
