# Generated by Django 4.2.28 on 2026-03-26 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_chordmelodyprogress_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='chordmelodyprogress',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eartrainingprogress',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
