# Generated by Django 4.2.28 on 2026-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_livesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
    ]
