# Generated by Django 4.2.28 on 2026-04-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_profile_course_completed'),
    ]

    operations = [
    ]
