# Generated by Django 4.2.28 on 2026-04-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20260409_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveSession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course_completed',
        ),
    ]
