# Generated by Django 4.2.28 on 2026-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_practicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
