# Generated by Django 4.2.28 on 2026-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_practicesession_end_time_practicesession_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership',
            field=models.CharField(choices=[('free', 'Free User'), ('standard', 'Standard User'), ('premium', 'Premium User')], default='free', max_length=20),
        ),
    ]
